branches:
  only:
    - master
    - stable
skip_tags: true
skip_commits:
  message: /(\[skip appveyor\]|\[appveyor skip\])/
image:
  - Visual Studio 2017
clone_depth: 1
install:
  - choco install nodejs-lts
  - yarn install
platform: x64
build: off
before_test:
  - cp settings\credentials.example.yaml settings\credentials.yaml
  - cp settings\configurations.example.yaml settings\configurations.yaml
test_script:
  - node --version
  - yarn --version
  - yarn test
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
deploy: off
