---
# Default prefixes of Bastion. This is permanent, i.e., once set, it'll stay
# the same until the database is reset.
# Although, you can use the `prefix` command to change server speific prefix.
prefixes:
  - "!"
  - "*"

# Default Presence of Bastion
presence:
  # Default status of Bastion.
  # Valid values are `online`, `idle`, `dnd` and `invisible`
  status: "dnd"
  # Default activity of Bastion
  activity:
    # Activity type.
    # Valid values are `PLAYING`, `LISTENING`, `WATCHING` and `STREAMING`.
    # Note that `STREAMING` activity will only work if a valid Twitch channel URL
    # is added in the `url` field below.
    type: "PLAYING"
    # Activity name.
    # The name of the activity.
    name: "with Ganymede"
    # Acitvity URL
    # Twitch channel URL for `STREAMING` activity.
    url: "https://twitch.tv/k3rn31p4nic"

# Scheduled Commands
scheduledCommands:
  # Command name
- command: command
  # Arguments for the command
  arguments: "command arguments"
  # Cron expression for the scheduler
  # Format:
  #   Second         0-59 or * or range
  #   Minute         0-59 or * or range
  #   Hour           0-23 or * or range
  #   Day of month   1-31 or * or range
  #   Month          1-12 or * or range
  #   Day of week    0-7 (0 or 7 is SUN) or * or range
  cronTime: "* * * * * *"
  # ID of the Discord Server where this command will be scheduled
  server: "134054417466911337"
  # ID of the Discord Channel where this command will be scheduled
  channel: "422946211761681337"

# Port used for the Status API.
# `PORT` environment variable overwrites this value.
port: 8377
